services:
  auth-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://postgres:5432/authdb
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_PRIVATE_KEY_PATH=file:/run/secrets/private.pem
      - JWT_PUBLIC_KEY_PATH=file:/run/secrets/public.pem
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - APP_BASE_URL=${APP_BASE_URL}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/main/resources/keys/private.pem:/run/secrets/private.pem:ro
      - ./src/main/resources/keys/public.pem:/run/secrets/public.pem:ro

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
